apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidates
  labels:
    app: candidates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidates
  template:
    metadata:
      labels:
        app: candidates
    spec:
      containers:
        - name: candidates
          image: kvmayer/go-candidates:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: candidates
spec:
  selector:
    app: candidates
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
